# Generated by Django 5.0.3 on 2024-04-01 12:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('All', '0002_recipe_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='recipe',
            old_name='User',
            new_name='user',
        ),
    ]
